<!DOCTYPE html>
<html>

<head>
	<title>Tienda</title>
	<link rel="stylesheet" href="./views/css/custom.css">
</head>

<body>
	<div class="container">
		<header class="row justify-content-between align-items-center">
			<h1 class="col-auto">Chat Room</h1>
			<nav class="col-auto">
				<ul class="nav">
					<li><a href="index.php">Inicio</a></li>
					<?php
                    if ($_SESSION['user']->getName() == "")
                    {
	                    echo '<li><a href="index.php?login">Login</a></li>';
                    }
                    else
                    {
	                    echo '<li><a href="index.php?login&logout">Salir</a></li>';
                    }
                    ?>
				</ul>
			</nav>
		</header>
		<main class="row">
			<div class="col-9">
				<div>
					<?php
                    if ($_SESSION['user']->getName() != "")
                    {
	                    echo '<form action="index.php?interactuar" method="post">
								<label class="form-label">¿Quieres publicar un nuevo mensaje?</label>
								<input type="text" class="form-control" name="mensaje">
								<div class="d-flex justify-content-between">
									<input type="submit" class="btn btn-primary" name="publicar" value="Publicar">
									<input type="submit" class="btn btn-primary" name="crearSala" value="Nueva Sala">
								</div>
							</form>';
                    }
                    ?>
				</div>
				<section>
					<h4>Mensajes</h4>
					<?php
                    foreach ($mensajes as $Mensaje)
                    {
	                    echo '<div class="row">';
	                    echo $Mensaje->getUser()->getName() . " - ";
	                    echo $Mensaje->getMensaje() . " - ";
	                    echo $Mensaje->getFecha();
	                    echo '</div>';
                    }
                    ?>
				</section>
			</div>

			<aside class="col-3 text-center">
				<h4>Usuarios conectados</h4>
				<?php
                foreach ($online as $User)
                {
	                echo $User->getName() . " - ";

                }
                ?>
			</aside>
		</main>
	</div>
</body>

</html>