<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php
        <?php 
        foreach ($mensajessala as $Mensaje) {
            echo '<p class="col-3 text-center">'.$Mensaje->getName().'</p>';
            echo '<div class="col-9 border-bottom">';
                echo '<p>'.$Mensaje->getMensaje().'</p>';
                echo '<p>'.$Mensaje->getFecha().'</p>';
            echo '</div>';
        }
        ?>
    ?>
</body>
</html>